"""empty message

Revision ID: cd209d9013ea
Revises: d68e7b84e571
Create Date: 2024-07-24 01:31:08.354659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd209d9013ea'
down_revision = 'd68e7b84e571'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_comment_media', type_='foreignkey')
        batch_op.create_foreign_key('fk_comment_media', 'media', ['media_id'], ['unique_id'])
        batch_op.drop_column('media_type')

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unique_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('episode_title', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('season_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('episode_number', sa.Integer(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.drop_constraint('fk_rating_media', type_='foreignkey')
        batch_op.create_foreign_key('fk_rating_media', 'media', ['media_id'], ['unique_id'])
        batch_op.drop_column('media_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_type', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_rating_media', 'media', ['media_id'], ['id'])

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('episode_number')
        batch_op.drop_column('season_number')
        batch_op.drop_column('episode_title')
        batch_op.drop_column('unique_id')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_type', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_comment_media', 'media', ['media_id'], ['id'])

    # ### end Alembic commands ###
