"""Add foreign keys to Comment and Rating models

Revision ID: fe6e025c4e6d
Revises: 
Create Date: 2024-07-23 04:16:22.880671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe6e025c4e6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_comment_media',  # Constraint name
            'media', ['media_id'], ['id']
        )

    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_rating_media',  # Constraint name
            'media', ['media_id'], ['id']
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.drop_constraint('fk_rating_media', type_='foreignkey')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_comment_media', type_='foreignkey')

    # ### end Alembic commands ###
